CREATE TABLE "assetPriceHistory" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assetPriceHistory_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"assetName" varchar(160) NOT NULL,
	"assetType" text DEFAULT 'stock_or_fund' NOT NULL,
	"currentValue" numeric(20, 2) NOT NULL,
	"cost" numeric(20, 2) NOT NULL,
	"pnl" numeric(20, 2) NOT NULL,
	"pnlPercent" numeric(12, 4) NOT NULL,
	"dailyChangePercent" numeric(12, 4) NOT NULL,
	"sourceDate" timestamp with time zone NOT NULL,
	"recordedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "googleOAuthConnections" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "googleOAuthConnections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"encryptedToken" text NOT NULL,
	"tokenExpiresAt" timestamp with time zone NOT NULL,
	"scopes" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "googleOAuthConnections_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "providentFundSnapshots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "providentFundSnapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"provider" varchar(80) DEFAULT 'SCB' NOT NULL,
	"fundName" varchar(160) DEFAULT 'Provident Fund' NOT NULL,
	"units" numeric(18, 4) NOT NULL,
	"memberUnits" numeric(18, 4),
	"employerUnits" numeric(18, 4),
	"nav" numeric(18, 4) NOT NULL,
	"netAssetValue" numeric(20, 2),
	"cumulativeReturnPercent" numeric(12, 4),
	"capital" numeric(18, 2),
	"valuationDate" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" text DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
ALTER TABLE "googleOAuthConnections" ADD CONSTRAINT "googleOAuthConnections_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "providentFundSnapshots" ADD CONSTRAINT "providentFundSnapshots_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "asset_price_history_asset_date_unique" ON "assetPriceHistory" USING btree ("assetName","sourceDate");